-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    c1: in std_logic;
    c2: in std_logic;
    c3: in std_logic;
    c4: in std_logic;
    q0: out std_logic);
end main;

architecture Behavioral of main is
begin
  q0 <= (((c1 AND c3) OR (c1 AND c2)) OR ((c1 AND c4) OR ((c3 AND c2) AND c4)));
end Behavioral;
